### ISSUE TITLE
Creating duplicate validator tx fails

### ISSUE THREAD

**Issue by mindstyle85** [harmony-one/harmony#2206] opened 2020-02-07 01:53 UTC
**Describe the bug**
so this is test case CV44 based on CV1 prep, where expected result is success but second "copy" of the validator isnt accepted into the quorum:

./hmy --node="https://api.s0.os.hmny.io" staking create-validator --validator-addr one1s7fp0jrmd97estwye3mhkp7xsqf42vn5x2sfqy --name mind --identity mind --website mind@harmony.one --security-contact mamapangaea --details "pink pony node runners" --rate 0.1 --max-rate 0.5 --max-change-rate 0.05 --min-self-delegation 5 --max-total-delegation 10000 --bls-pubkeys e429cbf74e8ab28ed295999d179ad79827c7febe0208a6145aa91bbb60b68a0b1907de4c38573352cafe00c8105b1116 --amount 10 --chain-id testnet 
Enter the bls passphrase:
{"transaction-receipt":"0x5bae61383656565e288f98d4d58fe57181be8d9c8d45ede702e8bede1d1e6eb2"}

this tx fails:

./hmy --node="https://api.s0.os.hmny.io" blockchain transaction-receipt 0x5bae61383656565e288f98d4d58fe57181be8d9c8d45ede702e8bede1d1e6eb2
{
  "id": "0",
  "jsonrpc": "2.0",
  "result": null
}

**Comment by rlan35** [comment] 2020-02-07 22:14
This is working as intended. The second validator with the duplicate key won't be selected. See the posterior expectation column ("Validator won't be selected as part of the committee, since it has a duplicate key as others.") in the spreadsheet.

**Comment by rlan35** [comment] 2020-02-07 22:15
Please double check and close the issue if no other issues.

**Comment by mindstyle85** [comment] 2020-02-07 22:30
Ok, i actually expected that it will show up in validators list but would never get selected since its a duplicate (hence presumption that the tx shouldnt fail). So to confirm, it is intended that the actual tx already fails here?

**Comment by rlan35** [comment] 2020-02-07 23:08
It doesn't fail. it got accepted. But the validator basically gets invalidated by doing that. We don't expect this case to happen that much tho.

**Comment by mindstyle85** [comment] 2020-02-07 23:36
but the tx is null?

./hmy --node="https://api.s0.os.hmny.io" blockchain transaction-receipt 0x5bae61383656565e288f98d4d58fe57181be8d9c8d45ede702e8bede1d1e6eb2
{
  "id": "0",
  "jsonrpc": "2.0",
  "result": null
}

**Comment by yelllowsin** [comment] 2020-03-02 17:04
@mindstyle85 tested this again with latest version from master on OSNT and hmy is throwing the correct message now, saying validator is duplicated. Maybe close this one?

```
./hmy --node="https://api.s0.os.hmny.io" staking create-validator --validator-addr one1zmtegpk65ghgwxzhq9q6hc6tjyj5z0ey8ge6zd --name Yelllowsin_2 --identity Yelllowsin_2 --website Yelllowsin_2 --security-contact Yelllowsin_2 --details "Yelllowsin_2" --rate 0.1 --max-rate 0.9 --max-change-rate 0.9 --min-self-delegation 1 --max-total-delegation 100000 --amount 90000 --bls-pubkeys 6379a296028744dc1377e22493280e926630412b1dfc18acebe54aa59dac6a00c79a905eefb177243e09664c2dbc5c05 --chain-id testnet
Enter the bls passphrase:
```

Result:

`[CreateValidator] one1zmtegpk65ghgwxzhq9q6hc6tjyj5z0ey8ge6zd: staking validator already exists -- 2020-03-02 13:38:31 +0000 UTC`

```
./hmy version
Harmony (C) 2020. hmy, version v300-d6ddd06 (deploy@harmony.one 2020-02-29T12:52:16+0100)
```

```
./node.sh -V
Harmony (C) 2020. harmony, version v5617-master-20191208.0-240-gc653234c (deploy@ 2020-02-29T12:52:03+0100)
```

**Closed** 2020-03-02 17:07 UTC
