### ISSUE TITLE
edit active flag to true is not updated until epoch change if BLS is elected

### ISSUE THREAD

**Issue by sophoah** [harmony-one/harmony#2433] opened 2020-03-09 15:57 UTC
**Describe the bug**
Edit active flag to true is not updated until epoch change if BLS is elected

As reported in #2431 MK5 set the validator flag to false when node1 is stopped. During that time, (ie wanna start node1) editing the flag to active is not working until epoch change. During that time, the validator is still elected.

Tested the edit-validator active tag set to true when validator is **not**  elected is updated staight

**To Reproduce**
Follow #2431 steps commented by myself
- try to set the flag to true and it wont be changed (while starting the node and waiting for epoch change) --> actually in this scenario, the flag doesn't become active but I think there is another issue (will add in the next comment tomorrow)
or 
wait for delegator to be kick out from committee (ie don't try to set to true) and try to set the flag to true after that

**Expected behavior**
set tag to true update should be fast nor wait for epoch update

**Environment (please complete the following information):**
 - harmony ```Harmony (C) 2020. harmony, version v5644-master-20191208.0-267-g87963bb7 (jenkins@ 2020-03-06T19:57:09+0000)```

**Additional context**

**Comment by janet-harmony** [comment] 2020-03-26 19:04
@sophoah @mindstyle85 
`getValidatorInformation` no longer has an active field. Can you check that this still applies to the `epos-status` field on the current OSTN, when its up?

**Comment by janet-harmony** [comment] 2020-03-29 23:42
Not able to reproduce, closing this issue.

**Closed by janet-harmony** 2020-03-29 23:42 UTC
Labels: pangaea1
