### ISSUE TITLE
OSTN - no epoch change, consensus true, BINGO-ing but no successful sig on shard 1

### ISSUE THREAD

**Issue by sophoah** [harmony-one/harmony#2589] opened 2020-03-24 11:37 UTC
**Describe the bug**
Shard 1 seems to buggy right now since rolling upgrade to harmony version ```version v5736-v1.3.5-45-ga817cbe9```

Validator keeps getting kick-out from committee.

Setting it to active will bring it online however signature never increase and actually validator information output will always stays as below:
```
  "result": {
    "current-epoch-performance": {
      "current-epoch-signing-percent": {
        "current-epoch-blocks-left": 38,
        "current-epoch-signed": 0,
        "current-epoch-signing-percentage": "0.000000000000000000",
        "current-epoch-to-sign": 0
      }
    },
```
Thing is during that non-election, we are actually BINGO-ing without issue, just that the block to sign never increase as above.

Checked a few other offline, and all are in shard1, other P-OPS also have the same issue

@JB273 checked watchdog and highlighted to something really off as the epoch is not the same as the other and is way behind
![image](https://user-images.githubusercontent.com/35721420/77421034-120e2f00-6e06-11ea-9aef-d6930c875356.png)

I moved to shard 3 my validator and it is now online and working as expected
```
  "result": {
    "current-epoch-performance": {
      "current-epoch-signing-percent": {
        "current-epoch-blocks-left": 23,
        "current-epoch-signed": 15,
        "current-epoch-signing-percentage": "1.000000000000000000",
        "current-epoch-to-sign": 15
      }
```

**To Reproduce**
1. create a validator node in shard 1

**Expected behavior**
It should work as other shard and not BINGO-ing and kickout node out of committee

**Screenshots**
N/A

**Environment (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by err0r711** [comment] 2020-03-24 11:41
same here

Shard 1  v5736-v1.3.5-45-ga817cbe9
                                                                                                                                               
  "result": {                                                                                                                                                        
    "current-epoch-performance": {                                                                                                                                   
      "current-epoch-signing-percent": {                                                                                                                             
        "current-epoch-blocks-left": 38,                                                                                                                             
        "current-epoch-signed": 0,                                                                                                                                   
        "current-epoch-signing-percentage": "0.000000000000000000",                                                                                                  
        "current-epoch-to-sign": 0

**Comment by yelllowsin** [comment] 2020-03-24 12:15
Having the same issue on shard 1. My node upgraded correctly but got kicked out of commitee. Also, via API epoch is stuck at 458 while blocks keep increasing, which matches what is on [watchdog](http://watchdog.hmny.io/report-staking):

```
./hmy blockchain latest-header
{
  "id": "0",
  "jsonrpc": "2.0",
  "result": {
    "blockHash": "0x92a3b331bbc2c1305aa59faedda219623f2f676fd35a971861046c6c617d9410",
    "blockNumber": 23176,
    "epoch": 458,
    "lastCommitBitmap": "fdfe7b38c27bddf7ff76",
    "lastCommitSig": "de0cd94169c9837008c7b58ba2b3404beca9b98a061aed46e672655c98fe093f7349a4323bf776a332c1a4e722e9970e8ba98d2c34283670a897415554cb35555e911f320d91e37ae7cbe9dab43d2e4ace0d63557fa849b0f45c9cd7ccc39986",
    "leader": "one1vaqzxt50ltk9hq4d44lgxmj4pj2x533fsp2acx",
    "shardID": 1,
    "timestamp": "2020-03-24 12:08:59 +0000 UTC",
    "unixtime": 1585051739,
    "viewID": 23176
  }
}
```

Activating the node again doesn't solve the issue as it doesn't sign any blocks and gets kicked out of commitee on next epoch:

```
 {
    "current-epoch-performance": {
      "current-epoch-signing-percent": {
        "current-epoch-blocks-left": 38,
        "current-epoch-signed": 0,
        "current-epoch-signing-percentage": "0.000000000000000000",
        "current-epoch-to-sign": 0
      }
    },
```

**Comment by BrunoMarshall** [comment] 2020-03-24 14:27
Several Validators(on shard1) are facing the same issue# for example: "GORDO" https://staking.harmony.one/validators/one1mpzx5wr2kmz9nvkhsgj6jr6zs87ahm0gxmhlck
![image](https://user-images.githubusercontent.com/35432495/77436468-d5c9d700-6de3-11ea-9bc7-97400d7e282f.png)

**Comment by janet-harmony** [comment] 2020-03-26 19:18
@sophoah 
Known issues with OSTN network Shard 1 & Shard 2 being down for some time, while we were testing some shard recovery processes.
Can you double-check that this issue still exists on the new network?

**Comment by BrunoMarshall** [comment] 2020-03-31 05:21
Hi Soph, we don´t have anymore the issue with epoch frozen "no epoch change" but some volunteers are reporting issue with signing, specially using multi-BLS keys.
@sophoah can we close this issue and possibly open one for signing related issue? like this : https://github.com/harmony-one/harmony/issues/2500

**Comment by janet-harmony** [comment] 2020-04-01 05:06
Not able to reproduce this specific issue, closing it.

**Closed by janet-harmony** 2020-04-01 05:06 UTC
Labels: pangaea2
