### ISSUE TITLE
Randomly miss the EPOS auction

### ISSUE THREAD

**Issue by sophoah** [harmony-one/harmony#2555] opened 2020-03-20 14:19 UTC
**Describe the bug**
it happens that my node is missing the epos auction even though  status was : 
```
    "currently-in-committee": false,
    "epos-status": "eligible to be elected next epoch",
```

**To Reproduce**
Steps to reproduce the behavior but it doesn't happened all the time :
1. be kick out from the committee and be in the status "not eligible to be elected next epoch"
2. edit validator active
3. wait for epoch change, nothing, happened, only at the next epoch i am part of the auction

**Expected behavior**
I should be able to participate to the EPOS selection straight away

**Screenshots**
N/A

**Environment (please complete the following information):**
 - OS: [Linux, MacOS]
- harmony version
```root@vmi334486:~/harmony# ./node.sh -V
Harmony (C) 2020. harmony, version v5702-v1.3.5-11-g31d64361 (jenkins@ 2020-03-19T17:40:10+0000)
```
**Additional context**
N/A

**Comment by mindstyle85** [comment] 2020-03-20 16:04
i can confirm this happened to me too, its a bit random though so sometimes it skips an epoch and sometimes it goes through..

**Comment by rlan35** [comment] 2020-03-26 23:40
https://github.com/harmony-one/harmony/pull/2612 this PR has the analysis and fix.

**Comment by LeoHChen** [comment] 2020-03-27 17:36
We are expecting a rolling upgrade of OSTN today with RJ's fix. Please confirm if it still the issue after today.

**Comment by mindstyle85** [comment] 2020-04-02 23:11
looks like this is fixed, closing

**Closed by mindstyle85** 2020-04-02 23:11 UTC
Labels: pangaea2
