### ISSUE TITLE
Token balances not loading (getBalance HRC20 calls), leading to DEXs like Viper, Mochi unusable

### ISSUE THREAD

**Issue by gupadhyaya** [harmony-one/harmony#3743] opened 2021-06-08 16:29 UTC
Currently there is an issue going on related to explorer nodes lagging due to increase in the number of transactions per block (more info [here](https://github.com/harmony-one/harmony/issues/3740)), and it is understandable that transaction confirmations could get impacted due to this, however, currently even the normal EVM calls like `getBalance` of a HRC20 token is slow and most times does not work, which is rendering DEXs like viper, mochi, almost unusable. Feels like this is more to do with rate limit of api calls (this [commit](https://github.com/harmony-one/harmony/commit/5e09b89322aa074e3872399bd2163480f19de62f) added the rate limit). The rate limit of 300 per second seems low, especially during the high load times. Note that the current spamming is adding 50-100 transactions every block, which also have several evm calls. Further, any DEX operation have several `getBalance` call for every token that any user has.

DEX like viper shows no balance or liquidity when it is unable to fetch them from the contracts (as shown below):

![deposits](https://user-images.githubusercontent.com/13854340/121222581-854d6680-c83b-11eb-8798-8488388ce74d.png)
![mining](https://user-images.githubusercontent.com/13854340/121222589-867e9380-c83b-11eb-9b24-976858b18156.png)

**Comment by LeoHChen** [comment] 2021-06-08 16:35
let me check if the rate limiter had reached the upper bound in the explorer nodes.

**Comment by LeoHChen** [comment] 2021-06-08 16:45
unfortunately, the PR to add rate limit is not merged yet, https://github.com/harmony-one/harmony/issues/3743

so I will have to do the following to mitigate the current issue.

1. add a customized build to check the rate limiter
1. increase the rate limit to 1000 by now

**Comment by gupadhyaya** [comment] 2021-06-08 17:12
Right now I see the explorer is insync. There are small windows where the explorer is insync and also see the DEX able to load balances and not have any issue. Any rationale for this @LeoHChen ?
<img width="1245" alt="Screen Shot 2021-06-08 at 10 08 35 AM" src="https://user-images.githubusercontent.com/13854340/121228363-8386a180-c841-11eb-92ea-df15d2a8cfb2.png">

Viper mining loads fine: 
![Uploading Screen Shot 2021-06-08 at 10.11.10 AM.png…]()

**Comment by LeoHChen** [comment] 2021-06-08 17:41
I have to restart the explorer nodes, they were out of sync mostly due to https://github.com/harmony-one/harmony/issues/3740

**Comment by gupadhyaya** [comment] 2021-06-08 17:48
> I have to restart the explorer nodes, they were out of sync mostly due to #3740

is regularly restarting explorer nodes a temporary solution until #3740 is resolved?

**Comment by LeoHChen** [comment] 2021-06-08 18:13
nodes are out of sync very fast, need to work on some automation solution to detect and restart harmony process as a mitigation right now

**Comment by LeoHChen** [comment] 2021-06-08 19:05
The problem is still the nodes out of sync issue.  I have added a solution to detect the node out-of-sync, and to restart the nodes. The cronjob will be checking/run every 15 minutes as temporary mitigation.  Closing this ticket, for now, #3740 is still the root cause.

**Closed by LeoHChen** 2021-06-08 19:05 UTC
Labels: high priority
