### ISSUE TITLE
Self same shard transaction

### ISSUE THREAD

**Issue by Daniel-VDM** [harmony-one/harmony#2055] opened 2020-01-09 00:53 UTC
**Describe the bug**
One can create a transaction to oneself within the same shard.

**To Reproduce**
1. Check out code with "sha1" commit
2. Build
3. Start localnet.
4. Send funds to oneself within the same shard 
5. `getTransactionReceipt` and `getTransactionByHash` with the resulting hash will work

**Expected behavior**
Unsure. We need to define what correct behavior is.

**Screenshots**
![image](https://user-images.githubusercontent.com/31291913/72028418-4b87c300-3237-11ea-80e9-73d633799b01.png)

**Comment by LeoHChen** [comment] 2020-01-10 22:48
@rlan35 , can you comment on this one?

**Comment by mindstyle85** [comment] 2020-01-10 23:14
afaik self sending is usually allowed, both with eth and btc for example

@SebastianJ also mentioned that in ETH you can use the self sending function with higher gas and same nonce, to cancel previous tx with the same nonce

**Comment by SebastianJ** [comment] 2020-01-11 04:45
Yes, in Ethereum you can cancel pending transactions (i.e. transactions in the mempool/not yet confirmed) by sending 0 ETH to your own address, using the exact same nonce as the stuck/pending transaction and increasing the gas price.

When the network picks up the 0 ETH tx with the higher gas fee it will automatically invalidate the previous stuck/pending transaction (since only one transaction is allowed for a given nonce).

I've done this countless of times on Ethereum with stuck transactions, it's a quite useful feature.

**Comment by LeoHChen** [comment] 2020-01-11 04:47
cool. so it is an intended behavior.  we can close this ticket.

**Closed by LeoHChen** 2020-01-11 04:47 UTC
Labels: design
