### ISSUE TITLE
state syncing is not working on banjo branch

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/harmony#691] opened 2019-04-08 03:04 UTC
**Describe the bug**

Using banjo branch, I launched a long running testnet and then I tried to join in the testnet using my linux devdesktop.  However, I got the following the error messages in the log.

I was running a daemon to do transactions with the blockchain constantly. 

```
DEBUG[04-08|02:59:12.412] processCommittedMessage error            port=9000 ip=52.8.49.119    error="invalid consensus message"
INFO [04-08|02:59:12.432] [SYNC] clean up inactive peers           port=9000 ip=52.8.49.119    activeNumber=20
INFO [04-08|02:59:12.435] syncing: Finished getting consensus block hashes. port=9000 ip=52.8.49.119
INFO [04-08|02:59:12.435] syncing: Finished generateStateSyncTaskQueue port=9000 ip=52.8.49.119    length=187
WARN [04-08|02:59:12.445] [DRG] Failed to verify the message signature port=9000 ip=52.8.49.119    Error="failed to verify the signature"
INFO [04-08|02:59:12.734] [SYNC] Finished downloadBlocks.          port=9000 ip=52.8.49.119
INFO [04-08|02:59:12.734] [SYNC] Current Block                     port=9000 ip=52.8.49.119    blockHex=0x44857b5e68420355d360a3c504d805ab268791b5899c68d4a04de6066446d7cb
ERROR[04-08|02:59:12.737] cannot create group sig mask: key not found port=9000 ip=52.8.49.119
ERROR[04-08|02:59:12.738]
########## BAD BLOCK #########
Chain config: {ChainID: 0 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0  ConstantinopleFix: 0 Engine: ethash}

Number: 2
Hash: 0xd1bd0d05cb27ceb7cce73db79b96664304b8d1b395fb1173fe30544e0febda41
        &{[] 1 77048 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] [] [195 214 34 152 240 168 82 72 228 208 89 0 45 172 77 100 203 83 144 222 46 155 20 39 81 114 138 192 37 214 217 219] [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] 77048}


Error: invalid merkle root (remote: be54bf87219e2c17de4547733c6efca87c9ab5b14fd50db4072201a9d6971b5e local: 1fe129513521d074fcdff422802c3e584e170aab6f1fb3271b4d895d97a42633)
##############################

DEBUG[04-08|02:59:12.738] Error adding new block to blockchain     port=9000 ip=52.8.49.119    Error="invalid merkle root (remote: be54bf87219e2c17de4547733c6efca87c9ab5b14fd50db4072201a9d6971b5e local: 1fe129513521d074fcdff422802c3e584e170aab6f1fb3271b4d895d97a42633)"
INFO [04-08|02:59:12.738] [SYNC] clean up inactive peers           port=9000 ip=52.8.49.119    activeNumber=20
DEBUG[04-08|02:59:12.799] [SYNC] IsOutOfSync                       port=9000 ip=52.8.49.119    otherHeight=189 myHeight=1
INFO [04-08|02:59:12.800] [SYNC] clean up inactive peers           port=9000 ip=52.8.49.119    activeNumber=20
DEBUG[04-08|02:59:12.800] [SYNC] node registration to peers        port=9000 ip=52.8.49.119    registrationNumber=3 activePeerNumber=20
```

**Comment by harmony-ek** [comment] 2019-04-08 19:51
Duplicate of #677.  Closing this and pursuing the issue there.

**Closed by harmony-ek** 2019-04-08 19:51 UTC
Labels: bug, high priority
