### ISSUE TITLE
[STN] STN nodes stuck in view change

### ISSUE THREAD

**Issue by JackyWYX** [harmony-one/harmony#3558] opened 2021-03-01 08:15 UTC
## Description

During testing the fault injected code with stream protocol on STN, it is observed that all nodes are stuck in view change mode. We'd better take a look at why this happens. https://watchdog.hmny.io/report-stn

Fault injected code: https://github.com/JackyWYX/harmony/tree/stn_downloader

Basically, the fault is injected in `tryCatchup`, which might cause consensus unable to collect enough signature. But ideally, the lagged node will catch up very quick and be able to participate in the view change process. So this unexpected problem needs better investigation.

```
func (consensus *Consensus) tryCatchup() error {
        ...
	if rand.Intn(20) == 0 {
		return errors.New("test error")
	}
        ... // insert blocks
}
```

**Comment by LeoHChen** [comment] 2021-03-01 09:11
There are two nodes didn't enter view change mode.

34.221.74.22
54.214.183.56

That's why view change can never be succeeded. Needs further investigation.  Those two nodes are still alive.

**Comment by LeoHChen** [comment] 2021-03-01 09:12
maybe it's a reproduce of this bug I found before, https://github.com/harmony-one/harmony/issues/3484

**Comment by JackyWYX** [comment] 2021-03-01 09:15
> There are two nodes didn't enter view change mode.
> 
> 34.221.74.22
> 54.214.183.56
> 
> That's why view change can never be succeeded. Needs further investigation. Those two nodes are still alive.

Nice observation. Also observed that these two node panic and exited with panic https://github.com/harmony-one/harmony/issues/3557.

**Comment by LeoHChen** [comment] 2021-03-01 09:31
found the following message in both nodes, after the last BINGO.

```json
{"level":"info","myBlock":32797,"myViewID":32809,"phase":"Commit","mode":"Normal","blockNum":32797,"viewID":32809,"blockHash":"0x0000000000000000000000000000000000000000000000000000000000000000","caller":"/home/yx/go/src/github.com/harmony-one/harmony/consensus/validator.go:282","time":"2021-02-27T17:51:24.534732983Z","message":"[OnCommitted] Failed finding a matching block for committed message"}
```

**Comment by LeoHChen** [comment] 2021-03-01 10:32
I checked these two nodes, the view change actually succeeded.

```json
{"level":"info","myBlock":32798,"myViewID":32813,"phase":"Announce","mode":"Normal","caller":"/home/yx/go/src/github.com/harmony-one/harmony/consensus/view_change.go:542","time":"2021-02-27T17:53:12.097453923Z","message":"onNewView === announce"}
```

**Comment by LeoHChen** [comment] 2021-03-01 10:33
> Observed that blockHash is 0x0000, is this expected?

That doesn't seem correct. Needs @rlan35 's help to identify the issue.

**Comment by LeoHChen** [comment] 2021-03-01 10:38
I also noticed on other nodes, this message with blockHash 0x000 also there. It is after the epoch change, in the last BINGO.

**Comment by LeoHChen** [comment] 2021-03-01 10:48
View Change actually succeeded, on node 54.202.26.122, log file, zerolog-harmony-2021-02-27T23-26-09.209.log

I found the following log line,

```json
{"level":"info","myBlock":32798,"myViewID":32813,"phase":"Announce","mode":"Normal","viewID":32813,"myKey":"3434351415d20b3b4a5014b9aca44703dfef332e50e008a59ca8d1f9bb41b0ea695fb74a0f9e346138a429d08c24c793","caller":"/home/yx/go/src/github.com/harmony-one/harmony/consensus/view_change.go:330","time":"2021-02-27T17:53:12.064722029Z","message":"[startNewView] viewChange stopped. I am the New Leader"}
```

**Comment by LeoHChen** [comment] 2021-03-01 10:51
not sure if we can recover the shard by restarting all nodes, let me try it.

**Comment by LeoHChen** [comment] 2021-03-01 11:16
can't recover the shard1 even after restart all nodes.

**Comment by JackyWYX** [comment] 2021-03-01 20:39
After a sync up with Leo, here is the observation by far:

1. The stuck block is at the epoch change.
2. Two nodes panics at nil map https://github.com/harmony-one/harmony/issues/3557 and exits. (The initial trigger is temporarily fixed but it reveals a rarely happened corner case. Need further investigation)
2. After the node restarted, view change actually succeeded with a new leader, but failed at new block proposal.
3. In new block committed message, the leader gives block hash 0x000000 that cause the consensus failure.
4. So the best guess by far is that there can be some bugs in async block proposal.

@rlan35 Please take a look at your convenience :)

**Comment by rlan35** [comment] 2021-03-02 01:51
The error means the node couldn't find the lastCommitSig from either DB nor memory (as in Committed Message). This could happen that the leader got the lastCommitSig but other node didn't because they didn't receive the Committed Message.

Actually one missing security logic in state sync logic is that the sync'ed block should be attached with the commit sig that's signed on it. Currently I think when we receive a new block, we only check the signature inside it against last block. But we actually need also the signature signed on this particular block to be confidently commit it. And with this sig data, it will also avoid such new block proposal issues due to missing sig data. @JackyWYX

**Comment by rlan35** [comment] 2021-03-02 01:55
Basically, for a sync'ed block to be valid, it should be contain not only the block itself, but also a signature data that's signed on it which can be verified. We've already added the sig data in the block structure for easy DB commitment.
![image](https://user-images.githubusercontent.com/1042540/109584853-3adb8180-7ab7-11eb-84f1-fc919b1e4611.png)

We should pass this sig in the block sync logic and verify it too. @JackyWYX can you work on this?

**Comment by sophoah** [comment] 2021-03-02 16:37
@rlan35 would the above security logic implementation and the async signature reception you implemented to reduce the time from 6 to 2 be conflicting ?

**Comment by rlan35** [comment] 2021-03-03 19:17
> @rlan35 would the above security logic implementation and the async signature reception you implemented to reduce the time from 6 to 2 be conflicting ?

what do you mean by async signature reception and 6 to 2?

**Comment by JackyWYX** [comment] 2021-03-16 09:27
@LeoHChen Hey Leo, I spotted another view change stuck on stressnet restart on shard 1. Do you mind taking a look?

**Comment by JackyWYX** [comment] 2021-03-16 09:36
Noticed that some shard 1 node should be in view change mode, but it is actually in normal mode. This can be caused by a successful stream sync:

![Screen Shot 2021-03-16 at 2 32 04 AM](https://user-images.githubusercontent.com/40162696/111287117-242d4280-8600-11eb-889f-3d5023084e8f.png)


```
// consensus/consensus_v2.go:340
case <-consensus.syncReadyChan:
  consensus.getLogger().Info().Msg("[ConsensusMainLoop] syncReadyChan")
  consensus.mutex.Lock()
  if consensus.blockNum < consensus.Blockchain.CurrentHeader().Number().Uint64()+1 {
	  consensus.SetBlockNum(consensus.Blockchain.CurrentHeader().Number().Uint64() + 1)
	  consensus.SetViewIDs(consensus.Blockchain.CurrentHeader().ViewID().Uint64() + 1)
	  mode := consensus.UpdateConsensusInformation()
	  consensus.current.SetMode(mode)
```

Which means, view change mode will be overriden by a normal mode after a successful sync. Do you think this might be the potential cause of this problem? And do you think we'd better protect the view change mode against a successful sync? @LeoHChen

**Comment by LeoHChen** [comment] 2021-03-16 09:43
Do you always set it to normal mode after syncing?  The node should go back to view change mode after a while if no new block is sync'ed.

**Comment by JackyWYX** [comment] 2021-03-16 09:46
Not always. 

After the initial sync iteration, downloader module will only inform this channel when it has some block to sync. So in this scenario, downloader should not set to normal again and again.

**Comment by JackyWYX** [comment] 2021-03-27 11:00
@LeoHChen Can we close this issue for now? We can open another issue if stuck again

**Closed** 2021-04-06 21:14 UTC
