### ISSUE TITLE
Test plan for #3790

### ISSUE THREAD

**Issue by JackyWYX** [harmony-one/harmony#3793] opened 2021-06-19 09:04 UTC
## Description

#3790 will do the explorer DB migration and then run explorer module under the new explorer DB schema. You can find all description in the PR description.

The testing cases are as follows:

0. Capture output of the following RPC call
    * `GetTransactionsCount`
    * `GetTransactionsHistory`
    * `GetStakingTransactionsHistory`
    * `getStakingTransactionsCount`
Objective is to confirm they are the same after the migration

1. After some time, the migration will be finished successfully with a log message in zerolog file:
```
{"level":"info","module":"explorer DB migration to 1.0.0","caller":"/home/yx/go/src/github.com/harmony-one/harmony/api/service/explorer/migration.go:106","time":"2021-06-19T07:48:00.873842447Z","message":"migration to 1.0.0 finished"}
```
2. The following RPC call will be unavailable during explorer migration:
    * `GetTransactionsCount`
    * `GetTransactionsHistory`
    * `GetStakingTransactionsHistory`
    * `getStakingTransactionsCount`
3. After the migration, the node is expected to catch up very quick. It is expected to observe the following message flooding in zerolog, which represents a data write has successed for a block in explorer db:
```
{"level":"info","module":"explorer storage","block number":13978376,"caller":"/home/yx/go/src/github.com/harmony-one/harmony/api/service/explorer/storage.go:135","time":"2021-06-19T09:01:58.008286598Z","message":"writing explorer DB"}
```
4. The explorer db will handle latest blocks at highest priority, and meanwhile it will catch up blocks that has left behind previously.
5. Check the results of 4 RPC calls given above without doing any new tx, the output should be the same as step 0
6. Check the results of 4 RPC calls given above with a new tx, they should give you the latest result of account transactions.

Please let me know if any of the description is unclear. Thanks.

**Comment by sophoah** [comment] 2021-06-19 18:47
test result

# step 0 and 5 - RPC result captured : 
`hmyv2_getTransactionsCount`
```bash
curl -ls --request POST 'https://rpc.s0.b.hmny.io' \
--header 'Content-Type: application/json' \
--data-raw '{
     "jsonrpc": "2.0",
     "id": 1,
     "method": "hmyv2_getTransactionsCount",
     "params": [
         "one1u6c4wer2dkm767hmjeehnwu6tqqur62gx9vqsd",
         "ALL"
     ]
}' | jq
```
```json
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": 239
}
```

after 
```json
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": 236
}
```
Note : different count

`hmyv2_getTransactionsHistory`
```bash
curl -ls --request POST 'https://rpc.s0.b.hmny.io' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc": "2.0",
    "id": 1,
    "method": "hmyv2_getTransactionsHistory",
    "params": [
        {
            "address": "one1u6c4wer2dkm767hmjeehnwu6tqqur62gx9vqsd",
            "pageIndex": 0,
            "pageSize": 1,
            "fullTx": true,
            "txType": "ALL",
            "order": "DESC"
        }
    ]
}' | jq
```
```json
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "transactions": [
      {
        "blockHash": "0x17ae7daae3cfcb6cd7c7574a56c8090068172c03350a5dd246b269bdf1aa683d",
        "blockNumber": 10064726,
        "ethHash": "0x7426c8a4dab3f990f4e5e322d883eb2a76fc65a97bc481f40fd38372913afd83",
        "from": "one1u6c4wer2dkm767hmjeehnwu6tqqur62gx9vqsd",
        "gas": 21000,
        "gasPrice": 1000000000,
        "hash": "0xe4955fecaced432418a3e162c91c7c23e0895a996295737b6174c85def3bb3f6",
        "input": "0x",
        "nonce": 281,
        "r": "0x5d8764b89c841caff84823fa1e8bd82ded984d75c0bcaa162053c398933df846",
        "s": "0x660cefffe878c7a3cafee5987c30a72bede197c6ba2998015245874c294b5c44",
        "shardID": 0,
        "timestamp": 1621856127,
        "to": "one1ay2a4w5tcc938pnpuk925rfe8x3epv6sl3wvh9",
        "toShardID": 0,
        "transactionIndex": 0,
        "v": "0x27",
        "value": 1e+18
      }
    ]
  }
}
```
after same output

`hmyv2_getStakingTransactionsCount`
```bash
curl -ls  --request POST 'https://rpc.s0.b.hmny.io' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc": "2.0",
    "id": 1,
    "method": "hmyv2_getStakingTransactionsCount",
    "params": [
        "one1u6c4wer2dkm767hmjeehnwu6tqqur62gx9vqsd",
        "ALL"
    ]
}' | jq
```
```json
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": 136
}
```

after
```json
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": 127
}
```
Note : different count

`hmyv2_getStakingTransactionsHistory`
```bash
curl -ls --request POST 'https://rpc.s0.b.hmny.io' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc": "2.0",
    "id": 1,
    "method": "hmyv2_getStakingTransactionsHistory",
    "params": [
        {
            "address": "one1u6c4wer2dkm767hmjeehnwu6tqqur62gx9vqsd",
            "pageIndex": 0,
            "pageSize": 1,
            "fullTx": true,
            "txType": "ALL",
            "order": "DESC"
        }
    ]
}' | jq 
```
```json
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "staking_transactions": [
      {
        "blockHash": "0x11123507fc8a1a0352731d475be5be7f242f492c421c401259c64c83a7e489b8",
        "blockNumber": 10456622,
        "from": "one1e5vu8sy6mypyel9xzynfsj22cfrll7tkz0v228",
        "gas": 45000,
        "gasPrice": 1000000000,
        "hash": "0x1c9ce2d87ec82fceea142c6368ca0a6b7191eabe19511c5f1ac6c5f06d94b7b8",
        "msg": {
          "amount": 5e+23,
          "delegatorAddress": "one1e5vu8sy6mypyel9xzynfsj22cfrll7tkz0v228",
          "validatorAddress": "one1u6c4wer2dkm767hmjeehnwu6tqqur62gx9vqsd"
        },
        "nonce": 33986,
        "r": "0x43ddf91414cb5e2ec8731b321b9aed93f15241be49b00f42a1e5906dfe2e5a90",
        "s": "0x2f106da93b2647e94e8c03907174e0297186eb3e98a66d68de2f78b307e63d60",
        "timestamp": 1622653740,
        "transactionIndex": 0,
        "type": "Delegate",
        "v": "0x27"
      }
    ]
  }
}
```
after same output

# step 1 - confirmed
```json
{"level":"info","module":"explorer DB migration to 1.0.0","progress":"0 / 31371","caller":"/mnt/jenkins/workspace/harmony-release/harmony/api/service/explorer/migration.go:64","time":"2021-06-19T20:22:23.30928788+02:00","message":"Start migration"}
{"level":"info","module":"explorer DB migration to 1.0.0","caller":"/mnt/jenkins/workspace/harmony-release/harmony/api/service/explorer/migration.go:69","time":"2021-06-19T20:25:49.083400391+02:00","message":"Finished migration. Starting value check"}
{"level":"info","module":"explorer DB migration to 1.0.0","caller":"/mnt/jenkins/workspace/harmony-release/harmony/api/service/explorer/migration.go:100","time":"2021-06-19T20:26:11.661811339+02:00","message":"migration to 1.0.0 finished"}
```

# step 2
I was monitoring the log and couldn't verify the RPC are not available/working during the migration

# step 3 - confirmed
```
{"level":"info","module":"explorer storage","block number":11190458,"caller":"/mnt/jenkins/workspace/harmony-release/harmony/api/service/explorer/storage.go:135","time":"2021-06-19T20:43:39.661284343+02:00","message":"writing explorer DB"}
{"level":"info","module":"explorer storage","block number":11190459,"caller":"/mnt/jenkins/workspace/harmony-release/harmony/api/service/explorer/storage.go:135","time":"2021-06-19T20:43:41.649967249+02:00","message":"writing explorer DB"}
{"level":"info","module":"explorer storage","block number":11190460,"caller":"/mnt/jenkins/workspace/harmony-release/harmony/api/service/explorer/storage.go:135","time":"2021-06-19T20:43:43.682517725+02:00","message":"writing explorer DB"}
```

# step 4
during the migration, explorer dashboard was working without issue

# step 6

**Comment by JB273** [comment] 2021-06-19 19:55
Test results:

**`GetTransactionsCount`**

```
curl -ls --request POST 'https://rpc.s0.b.hmny.io' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc": "2.0",
    "id": 1,
    "method": "hmyv2_getTransactionsCount",
    "params": [
        "one1gjsxmewzws9mt3fn65jmdhr3e4hel9xza8wd6t",
        "ALL"
    ]
}' | jq
```

```
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": 243
}
```

After:

```
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": 241
}

```
**`hmyv2_getTransactionsHistory`**

```
curl -ls --request POST 'https://rpc.s0.b.hmny.io' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc": "2.0",
    "id": 1,
    "method": "hmyv2_getTransactionsHistory",
    "params": [
        {
            "address": "one1gjsxmewzws9mt3fn65jmdhr3e4hel9xza8wd6t",
            "pageIndex": 0,
            "pageSize": 1,
            "fullTx": true,
            "txType": "ALL",
            "order": "DSC"
        }
    ]
}' | jq
```

```
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "transactions": [
      {
        "blockHash": "0xc449637835975f9f013dcb3173c7c5dd88dc60d4bb8aa5a50acb925e16ae6e27",
        "blockNumber": 250443,
        "ethHash": "0x35099cca66a51de07bbe4b8c023e3b477d5fce3e210f0c999742f8d1dafb6c4f",
        "from": "one1s0g5tt3se3qfwv9fn4zwtwvj4fdvefxvxn4nwh",
        "gas": 21000,
        "gasPrice": 1000000000,
        "hash": "0x86dacaedfdd1b3c93cb12624ae3324846f1a82a1380737783a052e07979f3f3b",
        "input": "0x",
        "nonce": 3665,
        "r": "0xf84a1cd1201d1e4fe3d0e8917f458d5cf92911d32088704290017fc4973cf88a",
        "s": "0x346a4409c7b4dddd5d98780e45e6355685c5152cd6aa125d46a73f01a0346918",
        "shardID": 0,
        "timestamp": 1592750532,
        "to": "one1gjsxmewzws9mt3fn65jmdhr3e4hel9xza8wd6t",
        "toShardID": 0,
        "transactionIndex": 0,
        "v": "0x27",
        "value": 5e+22
      }
    ]
  }
}
```

After:

```
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "transactions": [
      {
        "blockHash": "0xc449637835975f9f013dcb3173c7c5dd88dc60d4bb8aa5a50acb925e16ae6e27",
        "blockNumber": 250443,
        "ethHash": "0x35099cca66a51de07bbe4b8c023e3b477d5fce3e210f0c999742f8d1dafb6c4f",
        "from": "one1s0g5tt3se3qfwv9fn4zwtwvj4fdvefxvxn4nwh",
        "gas": 21000,
        "gasPrice": 1000000000,
        "hash": "0x86dacaedfdd1b3c93cb12624ae3324846f1a82a1380737783a052e07979f3f3b",
        "input": "0x",
        "nonce": 3665,
        "r": "0xf84a1cd1201d1e4fe3d0e8917f458d5cf92911d32088704290017fc4973cf88a",
        "s": "0x346a4409c7b4dddd5d98780e45e6355685c5152cd6aa125d46a73f01a0346918",
        "shardID": 0,
        "timestamp": 1592750532,
        "to": "one1gjsxmewzws9mt3fn65jmdhr3e4hel9xza8wd6t",
        "toShardID": 0,
        "transactionIndex": 0,
        "v": "0x27",
        "value": 5e+22
      }
    ]
  }
}
```

**`GetStakingTransactionsHistory`**

```
curl -ls --request POST 'https://rpc.s0.b.hmny.io' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc": "2.0",
    "id": 1,
    "method": "hmyv2_getStakingTransactionsHistory",
    "params": [
        {
            "address": "one1gjsxmewzws9mt3fn65jmdhr3e4hel9xza8wd6t",
            "pageIndex": 0,
            "pageSize": 1,
            "fullTx": true,
            "txType": "ALL",
            "order": "DESC"
        }
    ]
}' | jq 
```

```
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "staking_transactions": [
      {
        "blockHash": "0x201f5c66222ece3aa69e5233131924643f799bca9c5c16887eb2bd9ed3c1ff00",
        "blockNumber": 10193778,
        "from": "one1ceeclk4xpj230emd55nhlcdyx89xtpuy3cynpk",
        "gas": 45000,
        "gasPrice": 1000000000,
        "hash": "0x772ce67365bee94b02fff2a196f7b8bd21b3c7f9026975aebb5c623d80ed641f",
        "msg": {
          "amount": 5e+22,
          "delegatorAddress": "one1ceeclk4xpj230emd55nhlcdyx89xtpuy3cynpk",
          "validatorAddress": "one1gjsxmewzws9mt3fn65jmdhr3e4hel9xza8wd6t"
        },
        "nonce": 117,
        "r": "0xc5a968f080b717fd6ea5129cea7c87473f9b298604aa48be7e95412ff9d8f5b1",
        "s": "0x466a1cc1d860c0bd172fd1e7142551ddd96f0359ab8b091fc452303e0da40189",
        "timestamp": 1622115390,
        "transactionIndex": 0,
        "type": "Delegate",
        "v": "0x28"
      }
    ]
  }
}
```
after:

```
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "staking_transactions": [
      {
        "blockHash": "0x201f5c66222ece3aa69e5233131924643f799bca9c5c16887eb2bd9ed3c1ff00",
        "blockNumber": 10193778,
        "from": "one1ceeclk4xpj230emd55nhlcdyx89xtpuy3cynpk",
        "gas": 45000,
        "gasPrice": 1000000000,
        "hash": "0x772ce67365bee94b02fff2a196f7b8bd21b3c7f9026975aebb5c623d80ed641f",
        "msg": {
          "amount": 5e+22,
          "delegatorAddress": "one1ceeclk4xpj230emd55nhlcdyx89xtpuy3cynpk",
          "validatorAddress": "one1gjsxmewzws9mt3fn65jmdhr3e4hel9xza8wd6t"
        },
        "nonce": 117,
        "r": "0xc5a968f080b717fd6ea5129cea7c87473f9b298604aa48be7e95412ff9d8f5b1",
        "s": "0x466a1cc1d860c0bd172fd1e7142551ddd96f0359ab8b091fc452303e0da40189",
        "timestamp": 1622115390,
        "transactionIndex": 0,
        "type": "Delegate",
        "v": "0x28"
      }
    ]
  }
}
```

**`getStakingTransactionsCount`**

```
curl -ls  --request POST 'https://rpc.s0.b.hmny.io' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc": "2.0",
    "id": 1,
    "method": "hmyv2_getStakingTransactionsCount",
    "params": [
        "one1gjsxmewzws9mt3fn65jmdhr3e4hel9xza8wd6t",
        "ALL"
    ]
}' | jq
```

```
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": 123
}
```

After:

```
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": 111
}
```

**Comment by JackyWYX** [comment] 2021-06-19 20:51
When I did the migration value check, I did noticed that there were some duplicate transactions in explorer db before. So that I added the de-duplicate logic when comparing old and new transactions.

```
func (m *migrationV100) checkHashes(newHashes []common.Hash, oldTxs []*LegTxRecord) error {
	oldHashMap := make(map[common.Hash]struct{})
	for _, tx := range oldTxs {
		h := common.HexToHash(tx.Hash)
		oldHashMap[h] = struct{}{}
	}
	if len(newHashes) != len(oldHashMap) {
		return fmt.Errorf("transaction number not expected: %v / %v", len(newHashes), len(oldHashMap))
	}
	for _, h := range newHashes {
		if _, ok := oldHashMap[h]; !ok {
			return fmt.Errorf("transaction %v not found", h.String())
		}
	}
	return nil
}
```

It would help if you can check whether there are duplicate txn hashes before the migration. To use back up explorer db, you will need to:
1. Stop harmony process.
2. Backup the current explorer db, and rename backup db to the explorer db.
3. Use a harmony binary with version before the migration.
4. Start the harmony process.

Thanks!

**Comment by sophoah** [comment] 2021-06-21 04:59
closing this issue as test has been executed and discrepancies has been address due to duplication of the old DB

**Closed by sophoah** 2021-06-21 04:59 UTC
Labels: test
