### ISSUE TITLE
harmony metamask update

### ISSUE THREAD

**Issue by kafkesque** [harmony-one/harmony#4020] opened 2022-01-20 15:49 UTC
**Describe the bug**
/Apologies forward for the description I'm noob in this/
I have metamask  wallet with ledger address, & since I have moved the ONEs to that 

Before I have done any transaction I followed the following steps
- The ledger firmware is updated
- The newest Ethereum & Harmony app is installed in Ledger live
- Metamask has WEBHD setup & I have used the Ethereum app for the transaction 
- Ledger live is doesn't run in the background 
- Browser cookies & cache files are cleared
- Tried with both setup
A.  https://docs.harmony.one/home/network/wallets/browser-extensions-wallets/metamask-wallet setup
B.  https://docs.pokt.network/home/resources/public-rpc-endpoints/harmony-metamask

Still couldn't do any transaction, the token hasn't left the address after the ledger validation

**To Reproduce**
1. By each effort Metamask
 has provided default 0 nonce
 I added manually the nonce 
2. After  the ledger validation , the transaction was pending
3.   So I have sent extras gas fee to same adddress & nonce but still went through
Got this message  in the :
Transaction decoding is not available for chainId 1666600000
4. Reset Metamask  in settings

 - OS: [MacOS]

-**Additional context**

When I have tried to swap I got this message

`Swap failed: replacement fee too low (error={"code":-32603,"message":"[ethjs-query] while formatting outputs from RPC '{\"value\":{\"code\":-32603,\"data\":{\"code\":-32000,\"message\":\"replacement transaction underpriced\"}}}'","stack":"{\n \"code\": -32603,\n \"message\": \"[ethjs-query] while formatting outputs from RPC '{\\\"value\\\":{\\\"code\\\":-32603,\\\"data\\\":{\\\"code\\\":-32000,\\\"message\\\":\\\"replacement transaction underpriced\\\"}}}'\",\n \"stack\": \"Error: [ethjs-query] while formatting outputs from RPC '{\\\"value\\\":{\\\"code\\\":-32603,\\\"data\\\":{\\\"code\\\":-32000,\\\"message\\\":\\\"replacement transaction underpriced\\\"}}}'\\n at new i (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:18:148782)\\n at s (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:18:146325)\\n at Object.internal (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:18:146935)\\n at y.<anonymous> (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:1:210928)\\n at Object.h (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:18:35204)\\n at u (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:1:117610)\\n at y.a.emit (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:1:118146)\\n at y._setTransactionStatus (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-1.js:1:46740)\\n at y.setTxStatusFailed (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-1.js:1:45972)\\n at B._failTransaction (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:1:225990)\\n at B.approveTransaction (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:1:217659)\\n at async B.updateAndApproveTransaction (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:1:216902)\"\n}\n at new i (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:18:148782)\n at s (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:18:146325)\n at Object.internal (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:18:146935)\n at y.<anonymous> (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:1:210928)\n at Object.h (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:18:35204)\n at u (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:1:117610)\n at y.a.emit (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-0.js:1:118146)\n at y._setTransactionStatus (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-1.js:1:46740)\n at y.setTxStatusFailed (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-1.js:1:45972)\n at B._failTransaction (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:1:225990)\n at B.approveTransaction (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:1:217659)\n at async B.updateAndApproveTransaction (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:1:216902)"}, method="sendTransaction", transaction=undefined, code=REPLACEMENT_UNDERPRICED, version=providers/5.5.1)
`

**Comment by sophoah** [comment] 2022-02-01 12:08
there is a minimum of 30 gwei gas fee. I'll close this issue for now but feel free to reopen if that still doesn't work

**Comment by kafkesque** [comment] 2022-02-01 12:32
Why do you closing I have been waiting almost a month
& and you give me this as a solution? I have added more gwei it did'nt work

Sent from [ProtonMail](https://protonmail.ch), encrypted email based in Switzerland.

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
2022. február 1., kedd 12:08 keltezéssel, Soph ***@***.***> írta:

**Comment by sophoah** [comment] 2022-02-01 13:45
how much gwei did you added ? can you try with 40 ?

**Comment by kafkesque** [comment] 2022-02-01 13:58
between 30-40 but in default Metamask doesn't provide any nonce for the transaction  so I add manually and than block explorer doesn't recognize the transaction

**Comment by kafkesque** [comment] 2022-02-01 14:01
The real problem is not with gas

**Comment by sophoah** [comment] 2022-02-02 05:31
Hello,

Could you confirm the actual version:
1) which ledger nano ? S or X ?
2) Which version of the ledger firmware are you using ?
3) which version of the eth firmware are you using ?

on my end I was able to successfully transfer and do a swap with a Ledger Nano X running firmware 1.3.x and eth ledger app 1.9.9, all with metamask and nonce was shown correctly to me

**Comment by sophoah** [comment] 2022-02-02 05:35
> Also Why do I have to use the ethereum address if there is harmony & why metamask doesn't accept the harmony address?

Because metamask was build for Ethereum and doesn't recognized harmony bech32 address. Many chain including Harmony are eth EVM compatible, this capabaility facilitate the portage of dapp from eth to harmony much easier

Additionally, the harmony app is not required when you interacting with harmony via Metamask

**Comment by kafkesque** [comment] 2022-02-02 11:19
> Hello,
> 
> Could you confirm the actual version:
> 
> 1. which ledger nano ? S or X ?
> 2. Which version of the ledger firmware are you using ?
> 3. which version of the eth firmware are you using ?
> 
> on my end I was able to successfully transfer and do a swap with a Ledger Nano X running firmware 1.3.x and eth ledger app 1.9.9, all with metamask and nonce was shown correctly to me. Both test were done with a gas fee of 40 and 50.
> 
> edit: I also tested with a nano S with firmware 1.6.1 and eth app 1.7.0 and was able to successfully transact via metamask

Nano s
Firmware 2.1.0 (newest)
ETH  app Version 1.9.17 (newest)

**Comment by sophoah** [comment] 2022-02-02 11:22
Hello there, I am still waiting for Ledger if this is possible to downgrade the firmware to 1.6.1, there are multiple reports that 2.1.0 might be the root cause here.

**Comment by kafkesque** [comment] 2022-02-02 11:40
The bootloader doesn't work for me my ledger

**Comment by kafkesque** [comment] 2022-02-03 04:32
now it's working, thanks

**Comment by sophoah** [comment] 2022-02-03 04:42
@kafkesque what did you do to make it work ?

**Comment by kafkesque** [comment] 2022-02-03 04:50
I have done a test wrapped transaction and now it provides nonce

**Comment by sophoah** [comment] 2022-02-03 04:51
ok noted and are you able to send transaction with your ONE on metamask to any other address ? (ie try to send 0.001 ONE)

**Comment by kafkesque** [comment] 2022-02-03 04:56
> ok noted and are you able to send transaction with your ONE on metamask to any other address ? (ie try to send 0.001 ONE)

yes it works

**Comment by kafkesque** [comment] 2022-02-03 04:58
I guess the bug that to recognize the chain id, first have to wrap and than it works without wrap

**Comment by sophoah** [comment] 2022-03-04 03:32
closing this since there is a workaround thanks

**Closed by sophoah** 2022-03-04 03:32 UTC

**Comment by mrelber** [comment] 2022-03-28 21:05
Transaction decoding is not available for chainId 1666600000

hi i have this problem like u .please help me

**Comment by mrelber** [comment] 2022-03-28 21:05
> I guess the bug , that in order to recognize the chain id, first have to wrap and than it works without wrap

i can not understand this
