### ISSUE TITLE
Harmony v4925 (statically compiled) binary SIGSEGVs/SEGFAULTs on Ubuntu 18.04 / Ubuntu 19.04 / Debian 9

### ISSUE THREAD

**Issue by SebastianJ** [harmony-one/harmony#1811] opened 2019-11-07 13:46 UTC
**Describe the bug**
When installing a new node from scratch using the following steps:
1. `curl -LO https://raw.githubusercontent.com/harmony-one/harmony/master/scripts/node.sh && chmod u+x node.sh`
2. `./node.sh -t`

node.sh will download the harmony binary and then try to start - but it will terminate almost immediately after with the following error/stack trace:

```
INFO [11-07|14:36:56.327] SupportBeaconSyncing                     port=9000 ip=xx.xxx.xx.xx shardID=2 shardID=2
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x63 pc=0x7f12e8949448]
```

[Full stack trace available here](https://gist.github.com/SebastianJ/366a64ce29e4b7b26d2d9a659a479269).

Version of binary:
```
$ ./node.sh -V
Harmony (C) 2019. harmony, version v4925-master-20191029.0-2-gb3eeed6b (jenkins@ 2019-10-30T03:21:17+0000)
```

Linking status (i.e. fully static):
```
$ ldd harmony
not a dynamic executable
```

**To Reproduce**
On Ubuntu 18.04 / 19.04 / Debian 9:
1. `curl -LO https://raw.githubusercontent.com/harmony-one/harmony/master/scripts/node.sh && chmod u+x node.sh`
2. `./node.sh -t`

**Expected behavior**
Harmony binary should not SIGSEGV or SEGFAULT and run normally.

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04 LTS:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic
```
- OS: Ubuntu 19.04
- OS: Debian 9

**Additional context**
@mindstyle85 can successfully run the static binary on Ubuntu 16.04 - so the binary works partially on Ubuntu.

**Comment by SebastianJ** [comment] 2019-11-07 13:53
Related issue: https://github.com/harmony-one/go-sdk/issues/42

**Comment by mindstyle85** [comment] 2019-11-07 13:53
Node.sh version and binary version are both the same as above.

OS i tried and it doesnt work:
Debian 9 x64 (stretch)
Ubuntu 18.04. LTS
Ubuntu 19.04.

OS i tried and it works:
Debian 8 x64 (stretch)
Debian 10 x64 (stretch)

**Comment by mindstyle85** [comment] 2019-11-07 13:56
OS: Debian 9 x64 (stretch)
root@segfault3:~# chmod +x harmony
root@segfault3:~# ./node.sh -t
node.sh: autodetected BLS key file: /root/2c6281268374475e94f9e8dd8a078c21d6a3bf1be2b3e2dc4b1b497f89d881ac7cce008b18810adfa432fc4c617fd505.key
node.sh: binaries did not change
net.core.somaxconn = 1024
net.core.netdev_max_backlog = 65536
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_rmem = 4096 65536 16777216
net.ipv4.tcp_wmem = 4096 65536 16777216
net.ipv4.tcp_mem = 65536 131072 262144
node.sh: public IP address autodetected: 136.244.116.94
Enter passphrase for the BLS key file /root/2c6281268374475e94f9e8dd8a078c21d6a3bf1be2b3e2dc4b1b497f89d881ac7cce008b18810adfa432fc4c617fd505.key:
node.sh: ############### Running Harmony Process ###############
./node.sh: line 667:  1747 Segmentation fault      env "${ld_path_var}=$(pwd)" ./harmony "${args[@]}" "${@}"
node.sh: node process finished with status 139
node.sh: restarting in 10s...
node.sh: ############### Running Harmony Process ###############
./node.sh: line 667:  1752 Segmentation fault      env "${ld_path_var}=$(pwd)" ./harmony "${args[@]}" "${@}"
node.sh: node process finished with status 139
node.sh: restarting in 10s...

**Comment by mindstyle85** [comment] 2019-11-07 14:13
SIDENOTE: since hmy cli is also statically built now, we believe the same OSs will be an issue there too.

tried ubuntu 16.04 and it worked, and it doesnt work on 18.04 and 19.04

**Comment by LeoHChen** [comment] 2019-11-08 04:50
what is the instance type? Please report. Thanks.

**Comment by LeoHChen** [comment] 2019-11-08 04:53
Again, I would request a test on Amazon Linux and Amazon Linux 2.  We may not be able to support all the OS at this moment especially for statically linked binaries.  Thanks.

**Comment by SebastianJ** [comment] 2019-11-08 08:02
The tests for Ubuntu and Debian weren't performed on AWS instances - they were performed on VPS servers from OVH and Vultr. I personally tested on this server spec: [VPS SSD 3](https://www.ovh.com/asia/vps/vps-ssd.xml) and I think @mindstyle85 tested his setups on Vultr.

We tested on Amazon Linux and Amazon Linux 2 and the static binaries work on those OS:s (which I mentioned on Discord).

**Comment by sophoah** [comment] 2019-11-08 10:32
@LeoHChen I personally tested on vultr and scaleaway and the only difference that make things work or not are the OS version. Same issue as for the hmycli. I think @mindstyle85 tests were on vultr.

**Comment by mindstyle85** [comment] 2019-11-08 10:56
I tested with:
- home setup server, i5, 16gb RAM, 2TB HDD, with Ubuntu 16.04 lts
- Vultr: both high frequency compute and cloud compute instances with 2 cpu, 4+ GB RAM and NVME SSD disks
- AWS: tested on m5a.large instance with Ubuntu 18.04 and Amazon Linux 2

**Comment by LeoHChen** [comment] 2019-11-08 14:04
Hi, team,

I've tested the latest node.sh and run it on ubuntu16.04, ubuntu18.04, amazon linux, amazon linux 2, on t3.micro of AWS platforms. The harmony binary works fine on all platforms.  I highly doubt the VPS in the vultr platform is not properly configured, such as the OS is not x86_64 supported. I don't have time nor experience to test on Vultr platform.  Here is some of my basic understanding.

1) the OS and VPS platform have to be 64-bits (x86_64)
2) the virtualized CPU has to have some latest x86 instruction set to support our BLS library.

I suggest you run the following commands and provide the output in this ticket.  Also, I would ask someone like @sophoah or @mindstyle85 to summarize the data.  Especially important is to provide more spec of Vultr platform.

```uname -a
cat /proc/cpuinfo
```

I won't be able to spend too much time on this ticket. At this stage, if other platform is not working fine, I would focus on provide guidance on the working platforms, like on AWS at least t3.small as the preferred platform for all our validators, as it is proven and used internally.  Other platforms, the validators have to be tech-savvy and really learn to get the platform working.  The validators should be able to support each other in community.

**Comment by mindstyle85** [comment] 2019-11-08 14:46
Vultr Ubutnu 18.04 data (code when starting node.sh and the extra info for the instance): https://gist.github.com/mindstyle85/2eb7643e31f59b392316c088f1b4aa6a

**Comment by SebastianJ** [comment] 2019-11-08 14:50
I started a new t3.small instance and pulled node.sh from master. Still getting SIGSEGV:

Stack trace: https://gist.github.com/SebastianJ/5d5cc7260ae2e7e6682924c7f014d429

CpuInfo: https://gist.github.com/SebastianJ/92c0f15ded98b460892beea074d51f7d

**Comment by sophoah** [comment] 2019-11-08 15:14
test on AWS ubuntu 18 t3.small giving me errors for both the node and the hmycli
ubuntu@ip-172-31-20-184:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic
ubuntu@ip-172-31-20-184:~$

logs file with the cpuinfo :
https://pastebin.com/AFaE15Kv

**Comment by LeoHChen** [comment] 2019-11-09 08:02
@sophoah , I saw you have 

```
ubuntu@ip-172-31-20-184:~$ cat /proc/cpuinfo
processor       : 0
vendor_id       : AuthenticAMD
cpu family      : 23
model           : 1
model name      : AMD EPYC 7571
```

Are you using t3a.small?  Can you try t3.small?

**Comment by LeoHChen** [comment] 2019-11-09 08:04
The way I tested, using a new instance,

```
curl -LO https://harmony.one/node2.sh
chmod +x node2.sh
touch BLSKEY
touch blspass
./node2.sh -S -k BLSKEY -p blspass -t -T explorer -i 0
```

I was just using the explorer node to test the binary. I can test with a real key later then.   Can you guys try the explorer node mode at first.

**Comment by LeoHChen** [comment] 2019-11-09 08:08
```
[ec2-user@ip-172-31-20-250 ~]$ ./node2.sh -V
Harmony (C) 2019. harmony, version v4925-master-20191029.0-2-gb3eeed6b (jenkins@ 2019-10-30T03:21:17+0000)
[ec2-user@ip-172-31-20-250 ~]$ ./node2.sh -v
node2.sh: version: v1 20191105.1
```

**Comment by LeoHChen** [comment] 2019-11-09 08:08
I also opened the 9000 port on the node.

**Comment by sophoah** [comment] 2019-11-09 10:54
@LeoHChen so i created a new AWS instance t3.small (not t3a)
downloaded node.sh not node2.sh (which i compared later on are the same)
explorer run is working fine however when tried with a key it doesn't

logs are available here : https://pastebin.com/790TsCyb

For info, JB tested on his azure instance and it worked fine, not sure why. For us right now, the only fix is to use a ubuntu 16

**Comment by JB273** [comment] 2019-11-09 23:20
Used original Pangaea Node on Azure it has Ubuntu 18.04.3 installed, below are the outputs from the useful troubleshooting commands, hopefully it helps with the issue!:

**LD_LIBRARY_PATH=. ./harmony -version**
Harmony (C) 2019. harmony, version v4925-master-20191029.0-2-gb3eeed6b (jenkins@ 2019-10-30T03:21:17+0000)

**ldd harmony**
not a dynamic executable

**uname -a**
Linux JNB-Pangaea 5.0.0-1023-azure #24~18.04.1-Ubuntu SMP Wed Oct 2 20:23:29 UTC 2019 
 x86_64 x86_64 x86_64 GNU/Linux

**lsb_release -a**
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic

**cat /proc/cpuinfo**
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 79
model name      : Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz
stepping        : 1
microcode       : 0xffffffff
cpu MHz         : 2294.682
cache size      : 51200 KB
physical id     : 0
siblings        : 2
core id         : 0
cpu cores       : 2
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 20
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pd                                    pe1gb rdtscp lm constant_tsc rep_good nopl xtopology cpuid pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 movbe popcnt aes xsave avx f                                    16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti fsgsbase bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx smap xs                                    aveopt md_clear
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs
bogomips        : 4589.36
clflush size    : 64
cache_alignment : 64
address sizes   : 44 bits physical, 48 bits virtual
power management:

processor       : 1
vendor_id       : GenuineIntel
cpu family      : 6
model           : 79
model name      : Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz
stepping        : 1
microcode       : 0xffffffff
cpu MHz         : 2294.682
cache size      : 51200 KB
physical id     : 0
siblings        : 2
core id         : 1
cpu cores       : 2
apicid          : 1
initial apicid  : 1
fpu             : yes
fpu_exception   : yes
cpuid level     : 20
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pd                                    pe1gb rdtscp lm constant_tsc rep_good nopl xtopology cpuid pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 movbe popcnt aes xsave avx f                                    16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti fsgsbase bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx smap xs                                    aveopt md_clear
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs
bogomips        : 4589.36
clflush size    : 64
cache_alignment : 64
address sizes   : 44 bits physical, 48 bits virtual
power management:

**Comment by liuyangc3** [comment] 2019-11-13 03:10
same error with `node.sh` and `node2.sh`, Ubuntu 18.04.3 on droplet.
```console
$ ./node.sh -V
Harmony (C) 2019. harmony, version v4925-master-20191029.0-2-gb3eeed6b (jenkins@ 2019-10-30T03:21:17+0000)
$ ./node.sh -v
node.sh: version: v1 20191105.1

$ ./node2.sh -V
Harmony (C) 2019. harmony, version v4925-master-20191029.0-2-gb3eeed6b (jenkins@ 2019-10-30T03:21:17+0000)
$ ./node2.sh -v
node2.sh: version: v1 20191105.1
```

**Comment by LeoHChen** [comment] 2019-11-14 11:59
The issue was root caused by @harmony-ek , that the DNS records returned by testnet dns records are too long for dnsmasq to handle it properly, especially on ubuntu 18.04.  Once we reduced the number of hosts returned by dns record, the node2.sh actually works fine.  Please try again.  It's not the statically linked binary issue.

**Comment by mindstyle85** [comment] 2019-11-14 12:57
still the same issue on Ubuntu 18.04 bionic, tried node.sh and node2.sh

**Comment by mirrormirage0** [comment] 2019-11-14 13:10
https://pastebin.com/TrJP8G4d

Similar error with both node.sh and node2.sh
Ubuntu 18.04 AWS
Node version Harmony (C) 2019. harmony, version v4925-master-20191029.0-2-gb3eeed6b (jenkins@ 2019-10-30T03:21:17+0000)

**Comment by LeoHChen** [comment] 2019-11-18 09:40
@harmony-ek , please reduce the number of dns entries on s{0,1,2}.p.hmny.io.

**Comment by LeoHChen** [comment] 2019-11-18 09:42
@mirrormirage0 have you installed dnsmasq?  Please try to install dnsmasq on ubuntu, I forget to mention that.

**Comment by mirrormirage0** [comment] 2019-11-18 15:21
#Here are the additional steps I followed.

```
sudo systemctl disable systemd-resolved
sudo systemctl stop systemd-resolved
sudo rm /etc/resolv.conf
sudo apt-get install dnsmasq
sudo nano /etc/dnsmasq.conf
```

#uncomment the following lines
```
port=53
domain-needed
bogus-priv
strict-order
```

#add the following line
`listen-address=127.0.0.1`

#save the file

#edit resolv.conf
`sudo vim /etc/resolv.conf`

#add the following 2 lines
```
nameserver 127.0.0.1
nameserver 8.8.8.8
```

#Restart DNSMASQ
`sudo systemctl restart dnsmasq`

#check the status
'sudo systemctl status dnsmasq'

# Test if everything is fine
`dig A s2.p.hmny.io`

This should return all the 50 or so IP addresses

Now, make a prayer and start the node
`sudo ./node2.sh -t`

et voila! It breathes!
----------------------------------------------------------------------------------------------------------------------------
Note: These settings in resolv.conf will be lost if the server is restarted. The following should be added to /etc/netplan/ file on Ubuntu 18.04 
```
nameservers:
                addresses: [127.0.0.1,8.8.8.8]
```

**Comment by LeoHChen** [comment] 2019-11-18 20:23
that's great news! @mirrormirage0 , we shall include this setup info into our node.harmony.one document.

**Comment by sophoah** [comment] 2019-11-19 11:06
@LeoHChen just tested on a vultr ubuntu 19 and yes it also worked.

**Comment by mindstyle85** [comment] 2019-11-19 11:33
@LeoHChen thats great, but we already had this issue once on mainnet, and in the end the you just reduced the amount of DNS entries, which is a more clean solution it seems, and possibly no DNS in the end?

**Comment by LeoHChen** [comment] 2019-11-20 01:15
yes, we will move away from DNS, but not at the current high priority tasks.

**Comment by yelllowsin** [comment] 2020-03-03 17:46
@SebastianJ i think we can close this one, no? I am running statically linked binaries on mainet using Debian it is been a few days with no issues. There is an issue opened though regarding statically linked binaries #2351 but this one is not related to signal SIGSEGV: segmentation violation.

**Closed** 2020-03-23 14:21 UTC
