### ISSUE TITLE
 Catch all RPC error: validator stats not found: 0x0000000000000000000000000000000000000000

### ISSUE THREAD

**Issue by sophoah** [harmony-one/harmony#2197] opened 2020-02-06 13:36 UTC
**Describe the bug**
RPC error as shown below:
```bash
./hmy blockchain validator metrics one1u6c4wer2dkm767hmjeehnwu6tqqur62gx9vqsd -n https://api.s2.os.hmny.io
commit: v246-c28ff50, error: Catch all RPC error: validator stats not found: 0x0000000000000000000000000000000000000000
check hmy cookbook for valid examples or try adding a `--help` flag
```
**To Reproduce**
1 - make sure there are at least one active validator
2 - issue the command to gather the metric

**Expected behavior**
metric information on the validator

**Screenshots**
N/A

**Environment (please complete the following information):**
 - OS: [Linux, MacOS]
- Go environment [ ```go env``` ]

**Additional context**

**Comment by mindstyle85** [comment] 2020-02-06 16:50
tried it too,  can verify the issue

**Comment by fxfactorial** [comment] 2020-02-06 18:32
yep, knew about this issue a few days ago, was planning on checking

**Comment by fxfactorial** [comment] 2020-02-07 16:39
@sophoah actually I think this is expected because you hit up non beaconchain, aka not shard 0. 

```
-n https://api.s2.os.hmny.io
```

**Comment by sophoah** [comment] 2020-02-07 16:50
@fxfactorial  
./hmy blockchain validator metrics one1u6c4wer2dkm767hmjeehnwu6tqqur62gx9vqsd -n https://api.s0.os.hmny.io
commit: v255-cfaf9ff, error: Catch all RPC error: validator stats not found: 0x0000000000000000000000000000000000000000

**Comment by denniswon** [comment] 2020-02-07 23:39
Getting out of memory error when trying the rpc endpoint on a local net. Investigating.
```
ubuntu@ip-172-31-16-131:~/harmony-one/harmony (master) $ hmy blockchain validator metrics one1pdv9lrdwl0rg5vglh4xtyrv3wjk3wsqket7zxy -n http://127.0.0.1:9500
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0xba79a8, 0x16)
        /home/ubuntu/.gimme/versions/go1.13.6.linux.amd64/src/runtime/panic.go:774 +0x72 fp=0x7ffc0b2b2378 sp=0x7ffc0b2b2348 pc=0x438e12
runtime.sysMap(0xc000000000, 0x4000000, 0x1583398)
        /home/ubuntu/.gimme/versions/go1.13.6.linux.amd64/src/runtime/mem_linux.go:169 +0xc5 fp=0x7ffc0b2b23b8 sp=0x7ffc0b2b2378 pc=0x421ef5
runtime.(*mheap).sysAlloc(0x1560580, 0x2000, 0x0, 0x0)
        /home/ubuntu/.gimme/versions/go1.13.6.linux.amd64/src/runtime/malloc.go:701 +0x1cd fp=0x7ffc0b2b2460 sp=0x7ffc0b2b23b8 pc=0x41518d
runtime.(*mheap).grow(0x1560580, 0x1, 0xffffffff)
        /home/ubuntu/.gimme/versions/go1.13.6.linux.amd64/src/runtime/mheap.go:1255 +0xa3 fp=0x7ffc0b2b24b0 sp=0x7ffc0b2b2460 pc=0x42ffa3
runtime.(*mheap).allocSpanLocked(0x1560580, 0x1, 0x15833a8, 0x0)
        /home/ubuntu/.gimme/versions/go1.13.6.linux.amd64/src/runtime/mheap.go:1170 +0x266 fp=0x7ffc0b2b2530 sp=0x7ffc0b2b24b0 pc=0x42fe36
runtime.(*mheap).alloc_m(0x1560580, 0x1, 0x46002a, 0x0)
        /home/ubuntu/.gimme/versions/go1.13.6.linux.amd64/src/runtime/mheap.go:1022 +0xc2 fp=0x7ffc0b2b2580 sp=0x7ffc0b2b2530 pc=0x42f6d2
runtime.(*mheap).alloc.func1()
        /home/ubuntu/.gimme/versions/go1.13.6.linux.amd64/src/runtime/mheap.go:1093 +0x4c fp=0x7ffc0b2b25b8 sp=0x7ffc0b2b2580 pc=0x461f7c
runtime.(*mheap).alloc(0x1560580, 0x1, 0x1002a, 0x40000)
        /home/ubuntu/.gimme/versions/go1.13.6.linux.amd64/src/runtime/mheap.go:1092 +0x8a fp=0x7ffc0b2b2608 sp=0x7ffc0b2b25b8 pc=0x42f9ba
runtime.(*mcentral).grow(0x15613b8, 0x0)
        /home/ubuntu/.gimme/versions/go1.13.6.linux.amd64/src/runtime/mcentral.go:255 +0x7b fp=0x7ffc0b2b2648 sp=0x7ffc0b2b2608 pc=0x42191b
runtime.(*mcentral).cacheSpan(0x15613b8, 0x7fbef3ad8000)
        /home/ubuntu/.gimme/versions/go1.13.6.linux.amd64/src/runtime/mcentral.go:106 +0x2fe fp=0x7ffc0b2b26a8 sp=0x7ffc0b2b2648 pc=0x42143e
runtime.(*mcache).refill(0x7fbef3ad8008, 0x2a)
        /home/ubuntu/.gimme/versions/go1.13.6.linux.amd64/src/runtime/mcache.go:138 +0x85 fp=0x7ffc0b2b26c8 sp=0x7ffc0b2b26a8 pc=0x420ee5
runtime.(*mcache).nextFree(0x7fbef3ad8008, 0x158332a, 0x7fbef3ad8008, 0x8, 0xfffffffffffffff8)
        /home/ubuntu/.gimme/versions/go1.13.6.linux.amd64/src/runtime/malloc.go:854 +0x87 fp=0x7ffc0b2b2700 sp=0x7ffc0b2b26c8 pc=0x4159b7
runtime.mallocgc(0x180, 0xb96b80, 0x1, 0x1583400)
        /home/ubuntu/.gimme/versions/go1.13.6.linux.amd64/src/runtime/malloc.go:1022 +0x793 fp=0x7ffc0b2b27a0 sp=0x7ffc0b2b2700 pc=0x4162f3
runtime.newobject(0xb96b80, 0x4000)
        /home/ubuntu/.gimme/versions/go1.13.6.linux.amd64/src/runtime/malloc.go:1151 +0x38 fp=0x7ffc0b2b27d0 sp=0x7ffc0b2b27a0 pc=0x4166e8
runtime.malg(0xefb00008000, 0x1562c28)
        /home/ubuntu/.gimme/versions/go1.13.6.linux.amd64/src/runtime/proc.go:3232 +0x31 fp=0x7ffc0b2b2810 sp=0x7ffc0b2b27d0 pc=0x4421b1
runtime.mpreinit(...)
        /home/ubuntu/.gimme/versions/go1.13.6.linux.amd64/src/runtime/os_linux.go:324
runtime.mcommoninit(0x155b040)
        /home/ubuntu/.gimme/versions/go1.13.6.linux.amd64/src/runtime/proc.go:626 +0xc2 fp=0x7ffc0b2b2848 sp=0x7ffc0b2b2810 pc=0x43bbd2
runtime.schedinit()
        /home/ubuntu/.gimme/versions/go1.13.6.linux.amd64/src/runtime/proc.go:543 +0x72 fp=0x7ffc0b2b28a0 sp=0x7ffc0b2b2848 pc=0x43b832
runtime.rt0_go(0x7ffc0b2b29a8, 0x7, 0x7ffc0b2b29a8, 0x0, 0x7fbef2c54b97, 0x7fbef3903a80, 0x7ffc0b2b29a8, 0x7f3b2f170, 0x4642c0, 0x0, ...)
        /home/ubuntu/.gimme/versions/go1.13.6.linux.amd64/src/runtime/asm_amd64.s:214 +0x125 fp=0x7ffc0b2b28a8 sp=0x7ffc0b2b28a0 pc=0x4643f5                                                                                                                  2020-02-07  23:37:55 

```

**Comment by fxfactorial** [comment] 2020-02-11 23:17
fixed by @janet-harmony in https://github.com/harmony-one/go-sdk/pull/142   note: the validator must run at least one time in committee before the result is meaningful, might make RPC give back better error message but issue solved for now.

**Closed by fxfactorial** 2020-02-11 23:17 UTC

**Comment by janet-harmony** [comment] 2020-02-11 23:25
Fixed the command in the CLI.

Validator stats are not recorded until a validator has participated at least 1 round of the consensus committee. Added message in CLI to inform users.
```
$ hmyStaking blockchain validator metrics one1txy0a2szxlk7z0dvvfgv24kjjv60w2mcnyfl8a
Metrics are only available for Validators that have participated in consensus committee.
commit: v266-558cc6b-dirty, error: Catch all RPC error: validator stats not found: 0x5988fEaa0237EDe13DaC6250C556d29334F72B78
check hmy cookbook for valid examples or try adding a `--help` flag
```

**Comment by mindstyle85** [comment] 2020-02-11 23:39
Can this part be change to native one address string?

validator stats not found: 0x5988fEaa0237EDe13DaC6250C556d29334F72B78

**Comment by janet-harmony** [comment] 2020-02-25 04:09
Confirmed fixed.
```
$ hmyStaking blockchain validator metrics one1tqhlq4eemklv0l4qarlugt7qv8q6vdjssvuh6x
Metrics are only available for Validators that have participated in consensus committee.
commit: v287-06220f9, error: Catch all RPC error: validator stats not found: one1tqhlq4eemklv0l4qarlugt7qv8q6vdjssvuh6x
check hmy cookbook for valid examples or try adding a `--help` flag
```
